image:
  file: .gitpod/Dockerfile
tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
  - name: Login to Pulumi
    command: pulumi login
ports:
  - port: 3000
    onOpen: ignore
